// Wallet Payment Logic (Dummy wrapper as per your original code)
function startPaymentProcess() {
    const FEE = 1.20; 
    const fileInput = document.getElementById("pdfInput");
    const passInput = document.getElementById("pdfPassword");

    if (!fileInput || fileInput.files.length === 0) {
        alert("Please select a PDF file first!");
        return; 
    }
    if (passInput && passInput.value.trim() === "") {
        alert("Please enter the PDF Password first.");
        passInput.focus(); 
        return; 
    }

    // Checking if window.processWalletPayment exists like your original code
    if (typeof window.processWalletPayment === "function") {
        window.processWalletPayment(FEE, "White Aadhar Generation", function() {
            processPDFinPython(); 
        });
    } else {
        // If wallet logic is missing, proceed directly for testing
        processPDFinPython();
    }
}

// === SEND TO PYTHON BACKEND ===
async function processPDFinPython() {
    const fileInput = document.getElementById('pdfInput').files[0];
    const password = document.getElementById('pdfPassword').value;
    const isAutoMobile = document.querySelector('input[name="autoMobile"]:checked').value;

    const btnText = document.getElementById('btnText');
    const spinner = document.getElementById('loadingSpinner');
    
    // UI Loading State
    btnText.style.display = 'none';
    spinner.style.display = 'inline-block';

    const formData = new FormData();
    formData.append("pdf_file", fileInput);
    formData.append("password", password);
    formData.append("autoMobile", isAutoMobile);

    try {
        // Calling Python Flask Server (Make sure python is running on port 5000)
        const response = await fetch("http://127.0.0.1:5000/process_aadhaar", {
            method: "POST",
            body: formData
        });

        const data = await response.json();

        if (response.ok) {
            // Display Images generated by Python
            document.getElementById('frontImg').src = "data:image/png;base64," + data.front_image;
            document.getElementById('backImg').src = "data:image/png;base64," + data.back_image;
            
            // Set Download Links
            document.getElementById('downloadFront').href = "data:image/png;base64," + data.front_image;
            document.getElementById('downloadBack').href = "data:image/png;base64," + data.back_image;

            document.getElementById('outputArea').style.display = 'flex';
            triggerConfetti();
        } else {
            alert("Python Error: " + data.error);
        }
    } catch (error) {
        console.error(error);
        alert("Failed to connect to Python Server. Is app.py running?");
    } finally {
        // UI Reset
        btnText.style.display = 'inline';
        spinner.style.display = 'none';
    }
}

// === CONFETTI (PATAKA) CODE START ===
function triggerConfetti() {
    var duration = 3 * 1000; 
    var animationEnd = Date.now() + duration;
    var defaults = { startVelocity: 30, spread: 360, ticks: 60, zIndex: 0 };

    function randomInRange(min, max) {
        return Math.random() * (max - min) + min;
    }

    var interval = setInterval(function() {
        var timeLeft = animationEnd - Date.now();
        if (timeLeft <= 0) {
            return clearInterval(interval);
        }
        var particleCount = 50 * (timeLeft / duration);
        confetti(Object.assign({}, defaults, { particleCount, origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 } }));
        confetti(Object.assign({}, defaults, { particleCount, origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 } }));
    }, 250);
}
// === CONFETTI CODE END ===
